Wb/docker change
uw-it-aca/axdd-django-vue pull request #6
Opened 2021-04-23 21:01 UTC by SarthakSingh31

2021-04-28 17:42 UTC, charlon approved these changes

2021-04-29 20:10 UTC, abztrakt requested changes

2021-04-29 20:10 UTC, abztrakt commented on docker-compose.yml
> +      - ./myuw:/app/myuw
What should this be? If this is a generic "app_name" template, should that be ./app_name:/app/app_name instead?

2021-04-29 20:10 UTC, abztrakt commented on Dockerfile
> +ENV VUE_DEVTOOLS=$VUE_DEVTOOLS
Is this actually used by anything here?

2021-04-29 20:10 UTC, abztrakt commented on docker-compose.yml
> +      - statics-volume:/static
Why two volumes?

2021-04-29 20:10 UTC, abztrakt commented on docker-compose.yml
> +  statics-volume:
?

2021-04-29 20:10 UTC, abztrakt commented on docker/settings.py
> +    '../static/app_name/',
Why were we doing this relatively?

2021-04-29 22:51 UTC, charlon commented on docker/settings.py
> +    '../static/app_name/',
should be '/static/app_name/'

2021-04-29 22:54 UTC, charlon commented on webpack.config.js
> +        path: path.resolve('../static/app_name/'),
make this absolute!

2021-04-29 22:59 UTC, charlon commented on package.json
> +    "webpack": "^4.46.0",
update to webpack 5

2021-04-29 23:00 UTC, charlon commented on app_name/templates/index.html
>      <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
remove jquery!

2021-04-30 21:21 UTC, abztrakt approved these changes

2021-04-30 21:23 UTC, merged